from django.urls import path

from .study_views import (
    BookmarkAPIView,
    BookmarkDetailAPIView,
    ChapterTopicsAPIView,
    ClassSubjectsAPIView,
    ChapterObjectiveTestAPIView,
    ContentImportAPIView,
    FormulaAPIView,
    ImageUploadAPIView,
    NoteReorderAPIView,
    PracticeQuestionDetailAPIView,
    PracticeQuestionListAPIView,
    ProgressAPIView,
    ProgressUpdateAPIView,
    QuestionImportAPIView,
    ScheduledTestAPIView,
    SearchAPIView,
    StudyGoalAPIView,
    SubjectChaptersAPIView,
    SubjectOutlineAPIView,
    TopicAPIView,
    TopicNotesAPIView,
    TopicPracticeAPIView,
)
from .views import (
    ChapterBulkAPIView,
    ChapterAPIView,
    NoteBulkAPIView,
    NoteAPIView,
    SchoolClassBulkAPIView,
    SchoolClassAPIView,
    SubjectBulkAPIView,
    SubjectAPIView,
)

urlpatterns = [
    path("classes/bulk/", SchoolClassBulkAPIView.as_view(), name="class-bulk-create"),
    path("classes/", SchoolClassAPIView.as_view(), name="class-list-create"),
    path("classes/<uuid:uuid>/", SchoolClassAPIView.as_view(), name="class-detail"),
    path("subjects/bulk/", SubjectBulkAPIView.as_view(), name="subject-bulk-create"),
    path("subjects/", SubjectAPIView.as_view(), name="subject-list-create"),
    path("subjects/<uuid:uuid>/", SubjectAPIView.as_view(), name="subject-detail"),
    path("chapters/bulk/", ChapterBulkAPIView.as_view(), name="chapter-bulk-create"),
    path("chapters/", ChapterAPIView.as_view(), name="chapter-list"),
    path("chapters/<uuid:uuid>/", ChapterAPIView.as_view(), name="chapter-detail"),
    path("notes/bulk/", NoteBulkAPIView.as_view(), name="note-bulk-create"),
    path("notes/", NoteAPIView.as_view(), name="note-list"),
    path("notes/<uuid:uuid>/reorder/", NoteReorderAPIView.as_view(), name="note-reorder"),
    path("notes/<uuid:uuid>/", NoteAPIView.as_view(), name="note-detail"),
    path("classes/<uuid:uuid>/subjects/", ClassSubjectsAPIView.as_view(), name="class-subjects"),
    path("subjects/<uuid:uuid>/chapters/", SubjectChaptersAPIView.as_view(), name="subject-chapters"),
    path("subjects/<uuid:uuid>/outline/", SubjectOutlineAPIView.as_view(), name="subject-outline"),
    path("chapters/<uuid:uuid>/topics/", ChapterTopicsAPIView.as_view(), name="chapter-topics"),
    path("chapters/<uuid:uuid>/objective-test/", ChapterObjectiveTestAPIView.as_view(), name="chapter-objective-test"),
    path("topics/", TopicAPIView.as_view(), name="topic-list-create"),
    path("topics/<uuid:uuid>/", TopicAPIView.as_view(), name="topic-detail"),
    path("topics/<uuid:uuid>/notes/", TopicNotesAPIView.as_view(), name="topic-notes"),
    path("topics/<uuid:uuid>/practice-questions/", TopicPracticeAPIView.as_view(), name="topic-practice"),
    path("practice-questions/", PracticeQuestionListAPIView.as_view(), name="practice-question-list"),
    path("practice-questions/import/", QuestionImportAPIView.as_view(), name="practice-question-import"),
    path("practice-questions/<uuid:uuid>/", PracticeQuestionDetailAPIView.as_view(), name="practice-question-detail"),
    path("formulas/", FormulaAPIView.as_view(), name="formula-list"),
    path("search/", SearchAPIView.as_view(), name="academic-search"),
    path("bookmarks/", BookmarkAPIView.as_view(), name="bookmark-list"),
    path("bookmarks/<uuid:uuid>/", BookmarkDetailAPIView.as_view(), name="bookmark-detail"),
    path("progress/", ProgressAPIView.as_view(), name="study-progress"),
    path("progress/update/", ProgressUpdateAPIView.as_view(), name="study-progress-update"),
    path("progress/goal/", StudyGoalAPIView.as_view(), name="study-goal"),
    path("content/import/", ContentImportAPIView.as_view(), name="content-import"),
    path("uploads/", ImageUploadAPIView.as_view(), name="image-upload"),
    path("tests/", ScheduledTestAPIView.as_view(), name="scheduled-test-list"),
]
