# Generated by Django 6.1 on 2026-10-01 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target_type', models.CharField(choices=[('topic', 'Topic'), ('note', 'Note'), ('formula', 'Formula'), ('example', 'Example')], max_length=20)),
                ('target_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('prompt', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ScheduledTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('scheduled_on', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('scheduled_on', 'title'),
            },
        ),
        migrations.CreateModel(
            name='StudyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_target', models.PositiveSmallIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('sort_order', 'created_at')},
        ),
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='note',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['chapter_name'], name='academics_c_chapter_6bc7f6_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['title'], name='academics_c_title_a93c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_name'], name='academics_s_subject_424306_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['title'], name='academics_s_title_4e3c22_idx'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_questions', to='academics.chapter'),
        ),
        migrations.AddField(
            model_name='scheduledtest',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tests', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='studygoal',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_goal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='academics.chapter'),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_questions', to='academics.topic'),
        ),
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='academics.topic'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['title'], name='academics_n_title_e707dd_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['status', 'sort_order'], name='academics_n_status_2c1dee_idx'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='academics.note'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='academics.topic'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'target_type'], name='academics_b_user_id_5598f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'target_type', 'target_id')},
        ),
        migrations.AddIndex(
            model_name='scheduledtest',
            index=models.Index(fields=['scheduled_on', 'status'], name='academics_s_schedul_011a62_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['title'], name='academics_t_title_69d3ff_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['status', 'sort_order'], name='academics_t_status_f60f19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('chapter', 'title')},
        ),
        migrations.AddIndex(
            model_name='practicequestion',
            index=models.Index(fields=['difficulty'], name='academics_p_difficu_0a2714_idx'),
        ),
        migrations.AddIndex(
            model_name='practicequestion',
            index=models.Index(fields=['status'], name='academics_p_status_18286d_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'completed'], name='academics_u_user_id_ec3647_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['viewed_at'], name='academics_u_viewed__8e48e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.CheckConstraint(condition=models.Q(('topic__isnull', False), ('note__isnull', False), _connector='OR'), name='progress_has_topic_or_note'),
        ),
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('topic__isnull', False)), fields=('user', 'topic'), name='unique_user_topic_progress'),
        ),
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('note__isnull', False)), fields=('user', 'note'), name='unique_user_note_progress'),
        ),
    ]
