# Generated by Django 6.1 on 2026-10-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_study_topics_progress_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequestion',
            name='correct_option',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
